### ISSUE TITLE
rule_label unsupported

### ISSUE THREAD

**Issue by irussak3** [aws-ss/terraform-aws-wafv2#2]
Hi,

Can we add  rule_label supportץ

we just need to add this:

`      dynamic "rule_label" {
        for_each = lookup(rule.value, "rule_label", null) == null ? [] : [lookup(rule.value, "rule_label")]
        content {
          name = lookup(rule.value, "rule_label")
        }
      }`

**Comment by irussak3** [comment]
Changes can be seen in this [PR](https://github.com/aws-ss/terraform-aws-wafv2/pull/3)

**Comment by uyggnodoow** [comment]
Hello @irussak3 

Thank you. I merged your PR. #3
